clc;
close all;
clear all;
x1=input('Enter the first sequence');
x2=input('Enter the second sequence');
x1k=fft(x1);
x2k=fft(x2);
x3k=x1k.*x2k;
x3=ifft(x3k);
x4=cconv(x1,x2,max(length(x1),length(x2)));
subplot(4,1,1);
stem(x1);
xlabel('time--->');
ylabel('amplitude--->');
title('First input');
subplot(4,1,2);
stem(x2);
xlabel('time--->');
ylabel('amplitude--->');
title('Second input');
subplot(4,1,3);
stem(x3);
xlabel('time--->');
ylabel('amplitude--->');
title('Circular convolution using DFT & IDFT');
subplot(4,1,4);
stem(x4);
xlabel('time--->');
ylabel('amplitude--->');
title('Circular convolution');